# Generated by Django 5.1.4 on 2026-09-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('package_name', models.CharField(help_text="Google Play package id, e.g. 'org.telegram.messenger'.", max_length=255, unique=True)),
                ('name', models.CharField(help_text='Human-readable display name of the app.', max_length=255)),
                ('category', models.CharField(help_text='App category. One of: messenger, operator, video, word_game, chat_dating, social.', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the app is actively tracked (soft-delete flag).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when this row was created.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when this row was last updated.')),
            ],
            options={
                'db_table': 'apps',
                'managed': False,
            },
        ),
    ]
